# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

variables:
  buildConfiguration: 'Release'


steps:

#NuGet restore packages
- script: dotnet restore

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
  
# ...
# do this after other tasks such as building
- task: VSTest@2
  displayName: 'Perform Testing'
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'


# ...
# do this after you've built your app, near the end of your pipeline in most cases
# for example, you do this before you deploy to an Azure web app on Windows
- task: DotNetCoreCLI@2
  displayName: 'Preparation for deployment'
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True


# ...
# do this near the end of your pipeline in most cases
- task: PublishBuildArtifacts@1
